name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  token:
    description: "Github token"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
